### ISSUE TITLE
why not use AlbertForMaskedLM to load the model path?

### ISSUE THREAD

**Issue by autodataming** [rxn4chemistry/rxnmapper#5]
config.json

```json 
 "architectures": [
    "AlbertForMaskedLM"
  ],
```

core.py

```py 
MODEL_TYPE_DICT = {
    "bert": BertModel,
    "albert": AlbertModel,
    "roberta": RobertaModel
}
self.model_type=
        model_class = MODEL_TYPE_DICT[self.model_type]
        model = model_class.from_pretrained(
            self.model_path,
            output_attentions=True,
            output_past=False,
            output_hidden_states=False,
        )
```
I am confused that why not use AlbertForMaskedLM to load the model path.

```py
model =  AlbertForMaskedLM.from_pretrained(
            self.model_path,
            output_attentions=True,
            output_past=False,
            output_hidden_states=False,
        )
```

**Comment by pschwllr** [comment]
This would also work, but we don't need the MLM head after training anymore. So, for the atom-mapping, we only load the AlbertModel part (see also: https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_albert.py#L738)

We experimented with different autoencoding models (e.g. BERT, there are some nice layers/heads visualisations in the SI of our work, explaining the differences). That's why we kept the option to use a different model type.
